<#
.SYNOPSIS
    Generates Intune-ready detection and remediation scripts from a JSON configuration.

.DESCRIPTION
    Reads the sibling Invoke-RegistryConfigEngine.ps1 and produces two self-contained
    PowerShell scripts by replacing the engine's INJECTION_POINT region with the
    embedded config and the forced mode. The engine itself is the single source of
    truth — there is no separate template.

.PARAMETER ConfigPath
    Path to the JSON configuration file to package.

.PARAMETER OutputPath
    Directory where the Detect/Remediate scripts will be written. Default: current directory.

.PARAMETER Prefix
    Prefix for the generated filenames. Default: config filename without extension.

.PARAMETER VerboseLogging
    If specified, generated scripts run with $VerbosePreference = 'Continue', which
    surfaces all Write-Verbose/Debug-level engine output to Intune. No custom flag.

.EXAMPLE
    .\New-IntunePackage.ps1 -ConfigPath .\Configs\01-corporate-branding.json

.NOTES
    Author: Haakon Wibe
    Blog:   https://alttabtowork.com
#>

#Requires -Version 5.1

[CmdletBinding()]
param(
    [Parameter(Mandatory, Position = 0)]
    [ValidateScript({ Test-Path $_ -PathType Leaf })]
    [string]$ConfigPath,

    [Parameter(Position = 1)]
    [string]$OutputPath = ".",

    [Parameter()]
    [string]$Prefix,

    [Parameter()]
    [switch]$VerboseLogging
)

$ErrorActionPreference = 'Stop'

# Resolve the engine sibling
$enginePath = Join-Path $PSScriptRoot 'Invoke-RegistryConfigEngine.ps1'
if (-not (Test-Path -LiteralPath $enginePath)) {
    throw "Engine not found at: $enginePath"
}

# Read + validate the config (mirrors Get-Configuration's validation)
$configJson = Get-Content -Path $ConfigPath -Raw -Encoding UTF8
$config = $configJson | ConvertFrom-Json
if (-not $config.settings -or $config.settings.Count -eq 0) {
    throw "Configuration must contain at least one setting in the 'settings' array"
}
foreach ($setting in $config.settings) {
    if (-not $setting.scope) { throw "Each setting must have a 'scope'" }
    if (-not $setting.path)  { throw "Each setting must have a 'path'" }
}

# Read the engine and extract its version
$engineSrc = Get-Content -Path $enginePath -Raw -Encoding UTF8
$versionMatch = [regex]::Match($engineSrc, '\$script:EngineVersion\s*=\s*"([^"]+)"')
$engineVersion = if ($versionMatch.Success) { $versionMatch.Groups[1].Value } else { 'unknown' }

# A here-string is terminated by `'@` at column 0. JSON syntax doesn't allow that
# on its own line, but reject it loudly if encountered rather than producing a
# silently-broken script.
if ($configJson -match "(?m)^'@") {
    throw "Configuration JSON contains a line beginning with `'@` which would terminate the embedded here-string. Reformat the source JSON."
}

# Set up output directory + naming
if (-not (Test-Path -LiteralPath $OutputPath)) {
    New-Item -Path $OutputPath -ItemType Directory -Force | Out-Null
}
if ([string]::IsNullOrEmpty($Prefix)) {
    $Prefix = [System.IO.Path]::GetFileNameWithoutExtension($ConfigPath)
}

$timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz'
$sourceName = Split-Path -Leaf $ConfigPath
$injectionPattern = '(?s)#region INJECTION_POINT.*?#endregion'
$verboseLine = if ($VerboseLogging) { "`r`n`$VerbosePreference        = 'Continue'" } else { '' }

function Build-Script {
    param([Parameter(Mandatory)][ValidateSet('Detect', 'Remediate')][string]$Mode)

    $injection = @"
#region INJECTION_POINT
# Auto-generated by New-IntunePackage.ps1 — DO NOT EDIT
`$script:__EmbeddedConfig = @'
$configJson
'@
`$script:__ForcedMode     = '$Mode'
`$script:__ForcedEventLog = `$true$verboseLine
#endregion
"@

    $header = @"
# ============================================================================
# Registry Configuration Engine — $Mode (packaged for Intune)
# Engine version : $engineVersion
# Source config  : $sourceName
# Generated      : $timestamp
# DO NOT EDIT — regenerate via New-IntunePackage.ps1
# ============================================================================

"@

    # MatchEvaluator form avoids any $-escaping concerns in the replacement string.
    $body = [regex]::Replace($engineSrc, $injectionPattern, { param($m) $injection })

    $header + $body
}

$detectPath    = Join-Path $OutputPath "$Prefix-Detect.ps1"
$remediatePath = Join-Path $OutputPath "$Prefix-Remediate.ps1"

(Build-Script -Mode 'Detect')    | Set-Content -Path $detectPath    -Encoding UTF8 -NoNewline
(Build-Script -Mode 'Remediate') | Set-Content -Path $remediatePath -Encoding UTF8 -NoNewline

Write-Host "Generated:" -ForegroundColor Green
Write-Host "  $detectPath"
Write-Host "  $remediatePath"
Write-Host "Engine v$engineVersion | Settings groups: $($config.settings.Count)" -ForegroundColor Cyan
if ($VerboseLogging) { Write-Host "Verbose logging: enabled" -ForegroundColor Cyan }
