<#
.SYNOPSIS
    Registry Configuration - Detection Script
    Auto-generated by Registry Configuration Engine

.DESCRIPTION
    Prefer IPv4 over IPv6 - Required for Microsoft Global Secure Access

    Configuration Version: 1.0
    Generated: 2026-02-21 12:00:05

.NOTES
    Author: Haakon Wibe
    This script was generated from: 08-prefer-ipv4.json
#>

#Requires -Version 5.1

# ============================================================================
# 64-BIT ARCHITECTURE CHECK
# ============================================================================
if (-not [Environment]::Is64BitProcess -and [Environment]::Is64BitOperatingSystem) {
    $relaunchMsg = "Script launched in 32-bit PowerShell on 64-bit OS. Relaunching in 64-bit mode."
    Write-Output "[REGENGINE] [WARN] $relaunchMsg"
    try {
        $logDir = "$env:ProgramData\RegistryConfigEngine\Logs"
        if (-not (Test-Path $logDir)) { New-Item -Path $logDir -ItemType Directory -Force | Out-Null }
        $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        "[$timestamp] [WARN] [08-prefer-ipv4.json] $relaunchMsg" | Out-File -FilePath "$logDir\RegistryConfigEngine.log" -Encoding UTF8 -Append
    } catch { }
    try {
        $eventSource = "RegistryConfigEngine"
        if (-not [System.Diagnostics.EventLog]::SourceExists($eventSource)) {
            New-EventLog -LogName Application -Source $eventSource -ErrorAction SilentlyContinue
        }
        Write-EventLog -LogName Application -Source $eventSource -EventId 1000 -EntryType Warning -Message $relaunchMsg
    } catch { }
    $scriptPath = $MyInvocation.MyCommand.Definition
    $ps64 = "$env:SystemRoot\SysNative\WindowsPowerShell\v1.0\powershell.exe"
    $process = Start-Process -FilePath $ps64 -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$scriptPath`"" -Wait -PassThru -NoNewWindow
    exit $process.ExitCode
}

# ============================================================================
# EMBEDDED CONFIGURATION
# ============================================================================
$EmbeddedConfig = @'
{
  "$schema": "https://alttabtowork.com/schemas/registry-config-v1.json",
  "version": "1.0",
  "author": "Haakon Wibe",
  "description": "Prefer IPv4 over IPv6 - Required for Microsoft Global Secure Access",
  "created": "2026-01-28",
  "notes": [
    "Sets DisabledComponents to 0x20 (32) which prefers IPv4 over IPv6",
    "This is recommended for Global Secure Access (Entra Private Access / Internet Access)",
    "Reference: https://learn.microsoft.com/en-us/entra/global-secure-access/",
    "A reboot may be required for changes to take effect"
  ],
  "settings": [
    {
      "name": "Prefer IPv4 over IPv6",
      "description": "Configure Windows to prefer IPv4 connections over IPv6",
      "scope": "Machine",
      "path": "SYSTEM\\CurrentControlSet\\Services\\Tcpip6\\Parameters",
      "action": "Set",
      "rebootRequired": true,
      "values": [
        {
          "name": "DisabledComponents",
          "type": "DWord",
          "data": 32
        }
      ]
    }
  ]
}

'@

# ============================================================================
# REGISTRY CONFIGURATION ENGINE (Embedded)
# ============================================================================

$script:EngineVersion = "1.0.0"
$script:LogPrefix = "[REGENGINE]"
$script:Mode = "Detect"
$script:VerboseLogging = $false
$script:ConfigName = "08-prefer-ipv4.json"
$script:EventLogSource = "RegistryConfigEngine"
$script:EventLogName = "Application"
$script:FileLogDir = "$env:ProgramData\RegistryConfigEngine\Logs"
$script:FileLogPath = "$script:FileLogDir\RegistryConfigEngine.log"
$script:LogRetentionDays = 30

# Exit codes for Intune
$script:ExitCodes = @{
    Compliant       = 0
    NonCompliant    = 1
    RemediationOK   = 0
    RemediationFail = 1
}

function Invoke-LogCleanup {
    try {
        if (-not (Test-Path $script:FileLogPath)) { return }
        $cutoff = (Get-Date).AddDays(-$script:LogRetentionDays).ToString("yyyy-MM-dd")
        $lines = Get-Content -Path $script:FileLogPath -ErrorAction SilentlyContinue
        if (-not $lines -or $lines.Count -eq 0) { return }
        $kept = @()
        foreach ($line in $lines) {
            if ($line -match '^\[(\d{4}-\d{2}-\d{2})') {
                if ($Matches[1] -ge $cutoff) { $kept += $line }
            } else {
                $kept += $line
            }
        }
        $kept | Out-File -FilePath $script:FileLogPath -Encoding UTF8 -Force
    } catch { }
}

function Write-FileLog {
    param([string]$Message, [string]$Level = 'Info')
    try {
        if (-not (Test-Path $script:FileLogDir)) {
            New-Item -Path $script:FileLogDir -ItemType Directory -Force | Out-Null
        }
        $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        $levelTag = switch ($Level) {
            'Warning' { "WARN" }
            'Error'   { "ERROR" }
            'Success' { "OK" }
            default   { "INFO" }
        }
        $entry = "[$timestamp] [$levelTag] [$($script:ConfigName)] $Message"
        $entry | Out-File -FilePath $script:FileLogPath -Encoding UTF8 -Append
    } catch { }
}

function Write-Log {
    param([string]$Message, [string]$Level = 'Info', [int]$EventId = 1000, [switch]$VerboseOnly)
    if ($VerboseOnly -and -not $script:VerboseLogging) { return }
    $prefix = switch ($Level) {
        'Warning' { "[WARN]" }
        'Error'   { "[ERROR]" }
        'Success' { "[OK]" }
        default   { "[INFO]" }
    }
    Write-Output "$script:LogPrefix $prefix $Message"

    Write-FileLog -Message $Message -Level $Level

    if (([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
        try {
            if (-not [System.Diagnostics.EventLog]::SourceExists($script:EventLogSource)) {
                New-EventLog -LogName $script:EventLogName -Source $script:EventLogSource -ErrorAction SilentlyContinue
            }
            $entryType = switch ($Level) { 'Error' { 'Error' } 'Warning' { 'Warning' } default { 'Information' } }
            Write-EventLog -LogName $script:EventLogName -Source $script:EventLogSource -EventId $EventId -EntryType $entryType -Message $Message
        } catch { }
    }
}

function Get-UserProfileSIDs {
    $userSIDs = @()
    try {
        Get-ChildItem -Path "Registry::HKEY_USERS" -ErrorAction SilentlyContinue |
            Where-Object { $_.PSChildName -match '^S-1-5-21-|^S-1-12-1-' } |
            Where-Object { $_.PSChildName -notmatch '_Classes$' } |
            ForEach-Object {
                $sid = $_.PSChildName
                try {
                    $objSID = New-Object System.Security.Principal.SecurityIdentifier($sid)
                    $username = $objSID.Translate([System.Security.Principal.NTAccount]).Value
                } catch { $username = "Unknown" }
                $userSIDs += [PSCustomObject]@{
                    SID      = $sid
                    Username = $username
                    HivePath = "Registry::HKEY_USERS\$sid"
                }
            }
    } catch { }
    return $userSIDs
}

function Get-DefaultUserHive {
    $defaultUserPath = "$env:SystemDrive\Users\Default\NTUSER.DAT"
    $tempHiveKey = "HKU\DefaultUserTemp_$(Get-Random)"
    if (-not (Test-Path $defaultUserPath)) { return $null }
    try {
        $null = & reg.exe load $tempHiveKey $defaultUserPath 2>&1
        if ($LASTEXITCODE -ne 0) { return $null }
        return [PSCustomObject]@{
            HivePath    = "Registry::$tempHiveKey"
            TempKey     = $tempHiveKey
            NeedsUnload = $true
        }
    } catch { return $null }
}

function Dismount-DefaultUserHive {
    param([string]$TempKey)
    try {
        [gc]::Collect(); [gc]::WaitForPendingFinalizers()
        Start-Sleep -Milliseconds 500
        $null = & reg.exe unload $TempKey 2>&1
    } catch { }
}

function Convert-RegistryValue {
    param([string]$Type, $Value)
    switch ($Type.ToLower()) {
        'string'       { return [string]$Value }
        'expandstring' { return [string]$Value }
        'dword'        { return [int]$Value }
        'qword'        { return [long]$Value }
        'binary' {
            if ($Value -is [array]) { return [byte[]]$Value }
            elseif ($Value -match '^[0-9A-Fa-f,\s]+$') {
                $cleanValue = $Value -replace '\s+', ',' -replace ',+', ','
                return [byte[]]($cleanValue -split ',' | Where-Object { $_ } | ForEach-Object { [Convert]::ToByte($_.Trim(), 16) })
            }
            elseif ($Value -match '^(0x)?[0-9A-Fa-f]+$') {
                $hexString = $Value -replace '^0x', ''
                $bytes = @(); for ($i = 0; $i -lt $hexString.Length; $i += 2) { $bytes += [Convert]::ToByte($hexString.Substring($i, 2), 16) }
                return [byte[]]$bytes
            }
        }
        'multistring' { if ($Value -is [array]) { return [string[]]$Value } else { return [string[]]@($Value) } }
    }
}

function Get-RegistryTypeKind {
    param([string]$Type)
    switch ($Type.ToLower()) {
        'string'       { return [Microsoft.Win32.RegistryValueKind]::String }
        'expandstring' { return [Microsoft.Win32.RegistryValueKind]::ExpandString }
        'dword'        { return [Microsoft.Win32.RegistryValueKind]::DWord }
        'qword'        { return [Microsoft.Win32.RegistryValueKind]::QWord }
        'binary'       { return [Microsoft.Win32.RegistryValueKind]::Binary }
        'multistring'  { return [Microsoft.Win32.RegistryValueKind]::MultiString }
    }
}

function Expand-ConfigVariables {
    param($Value)
    if ($Value -is [string]) {
        $expanded = $Value
        @{
            '{{DATE}}'         = (Get-Date -Format "yyyy-MM-dd")
            '{{DATETIME}}'     = (Get-Date -Format "yyyy-MM-dd HH:mm:ss")
            '{{COMPUTERNAME}}' = $env:COMPUTERNAME
            '{{USERNAME}}'     = $env:USERNAME
            '{{DOMAIN}}'       = $env:USERDOMAIN
            '{{OSVERSION}}'    = [System.Environment]::OSVersion.Version.ToString()
            '{{ENGINEVERSION}}' = $script:EngineVersion
        }.GetEnumerator() | ForEach-Object { $expanded = $expanded -replace [regex]::Escape($_.Key), $_.Value }
        return $expanded
    }
    return $Value
}

function Compare-RegistryValue {
    param([string]$Path, [string]$Name, [string]$Type, $ExpectedValue, [string]$Comparison = 'Equals')
    try {
        $keyExists = Test-Path $Path
        $valueExists = $false
        $actualValue = $null
        if ($keyExists) {
            $currentValue = Get-ItemProperty -Path $Path -Name $Name -ErrorAction SilentlyContinue
            $valueExists = $null -ne $currentValue -and ($currentValue.PSObject.Properties.Name -contains $Name)
            if ($valueExists) { $actualValue = $currentValue.$Name }
        }
        if ($Comparison -eq 'Exists') {
            return @{ Match = $valueExists; Current = $actualValue; Reason = if ($valueExists) { "Value exists" } else { "Value does not exist" } }
        }
        if ($Comparison -eq 'NotExists') {
            return @{ Match = -not $valueExists; Current = $actualValue; Reason = if (-not $valueExists) { "Value does not exist (as expected)" } else { "Value exists (should not)" } }
        }
        if (-not $keyExists) { return @{ Match = $false; Current = $null; Reason = "Key does not exist" } }
        if (-not $valueExists) { return @{ Match = $false; Current = $null; Reason = "Value does not exist" } }
        $convertedExpected = Convert-RegistryValue -Type $Type -Value $ExpectedValue
        $match = $false; $reason = ""
        switch ($Comparison) {
            'Equals' {
                if ($Type.ToLower() -eq 'binary') {
                    $match = $null -ne $actualValue -and $actualValue.Length -eq $convertedExpected.Length -and -not (Compare-Object $actualValue $convertedExpected)
                } elseif ($Type.ToLower() -eq 'multistring') {
                    $match = $null -ne $actualValue -and -not (Compare-Object $actualValue $convertedExpected)
                } else { $match = $actualValue -eq $convertedExpected }
                $reason = if ($match) { "Values match" } else { "Values differ" }
            }
            'NotEquals' {
                if ($Type.ToLower() -eq 'binary') {
                    $match = $null -eq $actualValue -or $actualValue.Length -ne $convertedExpected.Length -or (Compare-Object $actualValue $convertedExpected)
                } elseif ($Type.ToLower() -eq 'multistring') {
                    $match = $null -eq $actualValue -or (Compare-Object $actualValue $convertedExpected)
                } else { $match = $actualValue -ne $convertedExpected }
                $reason = if ($match) { "Values differ (as expected)" } else { "Values match (should differ)" }
            }
            'GreaterThan'        { $match = $actualValue -gt $convertedExpected; $reason = if ($match) { "Value $actualValue > $convertedExpected" } else { "Value $actualValue is not > $convertedExpected" } }
            'GreaterThanOrEqual' { $match = $actualValue -ge $convertedExpected; $reason = if ($match) { "Value $actualValue >= $convertedExpected" } else { "Value $actualValue is not >= $convertedExpected" } }
            'LessThan'           { $match = $actualValue -lt $convertedExpected; $reason = if ($match) { "Value $actualValue < $convertedExpected" } else { "Value $actualValue is not < $convertedExpected" } }
            'LessThanOrEqual'    { $match = $actualValue -le $convertedExpected; $reason = if ($match) { "Value $actualValue <= $convertedExpected" } else { "Value $actualValue is not <= $convertedExpected" } }
            'Contains'           { $match = $actualValue -like "*$convertedExpected*"; $reason = if ($match) { "Value contains '$convertedExpected'" } else { "Value does not contain '$convertedExpected'" } }
            'StartsWith'         { $match = $actualValue -like "$convertedExpected*"; $reason = if ($match) { "Value starts with '$convertedExpected'" } else { "Value does not start with '$convertedExpected'" } }
            'EndsWith'           { $match = $actualValue -like "*$convertedExpected"; $reason = if ($match) { "Value ends with '$convertedExpected'" } else { "Value does not end with '$convertedExpected'" } }
        }
        return @{ Match = $match; Current = $actualValue; Reason = $reason }
    } catch {
        return @{ Match = $false; Current = $null; Reason = "Error: $_" }
    }
}

# ============================================================================
# MAIN EXECUTION
# ============================================================================

try {
    Invoke-LogCleanup
    $config = $EmbeddedConfig | ConvertFrom-Json
    Write-Log "Starting $($script:Mode) run on $env:COMPUTERNAME" -Level Info
    $compliant = $true
    $nonCompliantCount = 0
    $changesApplied = 0

    foreach ($settingGroup in $config.settings) {
        $scope = $settingGroup.scope
        $basePath = $settingGroup.path
        $action = if ($settingGroup.action) { $settingGroup.action } else { "Set" }

        $registryPaths = @()
        switch ($scope.ToLower()) {
            'machine' { $registryPaths += @{ Path = "HKLM:\$basePath"; Context = "Machine" } }
            'user' {
                Get-UserProfileSIDs | ForEach-Object {
                    $registryPaths += @{ Path = "$($_.HivePath)\$basePath"; Context = "User: $($_.Username)" }
                }
            }
            'defaultuser' {
                $defaultHive = Get-DefaultUserHive
                if ($defaultHive) {
                    $registryPaths += @{ Path = "$($defaultHive.HivePath)\$basePath"; Context = "Default User"; HiveInfo = $defaultHive }
                }
            }
        }

        foreach ($regPath in $registryPaths) {
            $fullPath = $regPath.Path

            if ($script:Mode -eq 'Detect') {
                switch ($action.ToLower()) {
                    'set' {
                        foreach ($value in $settingGroup.values) {
                            if ($value.skipDetection -eq $true) {
                                Write-Log "$($regPath.Context) | $basePath\$($value.name) - Skipped (skipDetection)" -Level Info -VerboseOnly
                                continue
                            }
                            $expandedValue = Expand-ConfigVariables -Value $value.data
                            $comparisonOperator = if ($value.comparison) { $value.comparison } else { 'Equals' }
                            $comparison = Compare-RegistryValue -Path $fullPath -Name $value.name -Type $value.type -ExpectedValue $expandedValue -Comparison $comparisonOperator
                            if (-not $comparison.Match) {
                                Write-Log "$($regPath.Context) | $basePath\$($value.name) - $($comparison.Reason) (expected: $expandedValue, current: $($comparison.Current))" -Level Warning -VerboseOnly
                                $compliant = $false
                                $nonCompliantCount++
                            } else {
                                Write-Log "$($regPath.Context) | $basePath\$($value.name) - Compliant" -Level Info -VerboseOnly
                            }
                        }
                    }
                    'delete' {
                        foreach ($value in $settingGroup.values) {
                            if (Test-Path $fullPath) {
                                $item = Get-ItemProperty -Path $fullPath -Name $value.name -ErrorAction SilentlyContinue
                                if ($null -ne $item -and ($item.PSObject.Properties.Name -contains $value.name)) {
                                    Write-Log "$($regPath.Context) | $basePath\$($value.name) - Value exists (should be deleted)" -Level Warning -VerboseOnly
                                    $compliant = $false
                                    $nonCompliantCount++
                                } else {
                                    Write-Log "$($regPath.Context) | $basePath\$($value.name) - Compliant (value absent)" -Level Info -VerboseOnly
                                }
                            }
                        }
                    }
                    'deletekey' {
                        if (Test-Path $fullPath) {
                            Write-Log "$($regPath.Context) | $basePath - Key exists (should be deleted)" -Level Warning -VerboseOnly
                            $compliant = $false
                            $nonCompliantCount++
                        } else {
                            Write-Log "$($regPath.Context) | $basePath - Compliant (key absent)" -Level Info -VerboseOnly
                        }
                    }
                }
            }
            elseif ($script:Mode -eq 'Remediate') {
                switch ($action.ToLower()) {
                    'set' {
                        if (-not (Test-Path $fullPath)) {
                            New-Item -Path $fullPath -Force | Out-Null
                            Write-Log "$($regPath.Context) | Created key: $basePath" -Level Info -VerboseOnly
                        }
                        foreach ($value in $settingGroup.values) {
                            if ($value.comparison -eq 'NotExists') {
                                if (Test-Path $fullPath) {
                                    $item = Get-ItemProperty -Path $fullPath -Name $value.name -ErrorAction SilentlyContinue
                                    if ($null -ne $item -and ($item.PSObject.Properties.Name -contains $value.name)) {
                                        Remove-ItemProperty -Path $fullPath -Name $value.name -Force
                                        Write-Log "$($regPath.Context) | Deleted (NotExists): $basePath\$($value.name)" -Level Info -VerboseOnly
                                        $changesApplied++
                                    }
                                }
                                continue
                            }
                            $expandedValue = Expand-ConfigVariables -Value $value.data
                            $convertedValue = Convert-RegistryValue -Type $value.type -Value $expandedValue
                            $valueKind = Get-RegistryTypeKind -Type $value.type
                            Set-ItemProperty -Path $fullPath -Name $value.name -Value $convertedValue -Type $valueKind
                            Write-Log "$($regPath.Context) | Set $basePath\$($value.name) = $expandedValue" -Level Info -VerboseOnly
                            $changesApplied++
                        }
                    }
                    'delete' {
                        foreach ($value in $settingGroup.values) {
                            if (Test-Path $fullPath) {
                                $item = Get-ItemProperty -Path $fullPath -Name $value.name -ErrorAction SilentlyContinue
                                if ($null -ne $item -and ($item.PSObject.Properties.Name -contains $value.name)) {
                                    Remove-ItemProperty -Path $fullPath -Name $value.name -Force
                                    Write-Log "$($regPath.Context) | Deleted value: $basePath\$($value.name)" -Level Info -VerboseOnly
                                    $changesApplied++
                                }
                            }
                        }
                    }
                    'deletekey' {
                        if (Test-Path $fullPath) {
                            Remove-Item -Path $fullPath -Recurse -Force
                            Write-Log "$($regPath.Context) | Deleted key: $basePath" -Level Info -VerboseOnly
                            $changesApplied++
                        }
                    }
                }
            }

            if ($regPath.HiveInfo -and $regPath.HiveInfo.NeedsUnload) {
                Dismount-DefaultUserHive -TempKey $regPath.HiveInfo.TempKey
            }
        }
    }

    if ($script:Mode -eq 'Detect') {
        if ($compliant) {
            Write-Log "COMPLIANT - All settings are correct" -Level Success
            exit $script:ExitCodes.Compliant
        } else {
            Write-Log "NON-COMPLIANT - $nonCompliantCount setting(s) need remediation" -Level Warning
            exit $script:ExitCodes.NonCompliant
        }
    } else {
        Write-Log "SUCCESS - $changesApplied change(s) applied" -Level Success
        exit $script:ExitCodes.RemediationOK
    }
}
catch {
    Write-Log "ERROR - $_" -Level Error
    exit 1
}
